# Use the Ballerina base image
FROM ballerina/ballerina:swan-lake

# Create a directory to store the Ballerina service
WORKDIR /usr/src/app

# Copy the Ballerina service file and other project files
COPY performance_management_service.bal .
COPY ballerina.conf .
COPY graphql/ ./graphql
COPY mongodb/ ./mongodb

# Expose the port your Ballerina service will run on
EXPOSE 9090

# Command to run your Ballerina service
CMD ballerina run performance_management_service.bal
